version: "3.7"
services:
  app:
    build:
      args:
        user: matheusbrdev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: matheusbrdev/php
    container_name: name-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/xdebug/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    networks:
      - nameNetwork

  db:
    image: mysql:5.7
    container_name: name-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - nameNetwork

  nginx:
    image: nginx:alpine
    container_name: name-server
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nameNetwork

networks:
  nameNetwork:
    driver: bridge
