version: '3'

services:
  cteste-app:
    image: local/container-php:latest
    hostname: cteste-app
    container_name: cteste-app
    restart: always
    volumes:
      - ./:/var/www/html/

    security_opt:
      - no-new-privileges:true
    ports:
      - 8080:80
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"