version: "3.7"
services:
  app:
    build:
      args:
        user: matheusbrdev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: matheusbrdev/php-7.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: name-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nameNetwork

  nginx:
    image: nginx:alpine
    container_name: name-server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nameNetwork

networks:
  nameNetwork:
    driver: bridge
